version: '3'
services:
  postgres:
    container_name: migrator_pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgre_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  mongo:
    container_name: migrator_mg
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/