spring:
  application:
    name: migrator
  r2dbc:
    username: admin
    password: admin
    url: r2dbc:postgresql://172.17.0.1:5432/postgre_db
  data:
    mongodb:
#      database: smart_resident
#      uri: mongodb://10.35.38.3:27017
      uri: mongodb://admin:password@172.17.0.1:27017/demo?authSource=admin
      database: demo
    r2dbc:
      repositories:
        enabled: true
  flyway:
    url: jdbc:postgresql://172.17.0.1:5432/postgre_db
    password: admin
    user: admin